const translations = {
  fr: {
    
    'order-info-title': 'Information sur les commandes',
    'order-info-text': 'Ces voitures sont disponibles sur commande. Contactez-nous pour plus d\'informations',
    'no-order-cars': 'Aucune voiture sur commande',
    'no-order-message': 'Aucune voiture disponible sur commande pour le moment.',
    'order-description': 'Voitures disponibles sur commande',
    'about': 'À propos',
    'contact': 'Contact',
    
    'location': 'Emplacement',
    'Sur-Commande': 'Sur Commande',
    'back': 'Retour',
    'copyright': '© 2025 Samy Auto. Tous droits réservés.',
    'welcome-subtitle': 'Découvrez notre collection de voitures disponibles immédiatement ou sur commande',
    'view-cars': 'Voir les voitures',
    'welcome-title': 'Bienvenue chez Samy Auto',
    'pret': 'Prêt à partir',
    'Voitures Disponibles': 'Voitures Disponibles',
    'available-description': 'Voitures prêtes',
    'view-more': 'Voir Plus',
    'car-not-found': 'Voiture non trouvée',
    'loading-error': 'Erreur lors du chargement',
    'description': 'Description:',
    'location-btn': 'Localisation',
    'call-btn': 'Appeler',
    'phone-numbers': 'Numéros de téléphone:',
    'call': 'Appeler',
    'copy': 'Copier',
    'copied': 'Copié!',
    'other-cars': 'Autres voitures disponibles',
    'back-to-list': 'Retour à la liste',
    'state': 'Etat',
    'year': 'Année',
    'finish': 'Finition',
    'colors': 'Couleurs',
    'motor': 'Motor',
    'gearbox': 'Boite',
    'new': 'Neuf',
    'used': 'Occasion',
    'luxury': 'Luxe',
    'economical': 'Économique',
    'suv': 'SUV',
    'citadine': 'Citadine',
    'En': 'Essence',
    'diesel': 'Diesel',
    'hybrid': 'Hybride',
    'information': 'Informations principales',
    'boit_manuelle': 'Manuelle',
    'technical_specs': 'Spécifications techniques',
    'basic_details': 'Détails de base',
    'Power': 'Puissance',
    'Cylindre': 'Cylindres',
    'ABS': 'ABS',
    'Radar stationnement avant': 'Radar stationnement avant',
    'Radar stationnement arrière': 'Radar stationnement arrière',
    'Climatisation': 'Climatisation',
    'Assistance Au Freinage': 'Assistance Au Freinage',
    'Contrôle De Stabilité': 'Contrôle de stabilité',
    'toit ouvrant': 'Toit ouvrant',
    'Disponible': 'Disponible',
    'Sur command': 'Sur commande',
    'Voitures Sur Commande': 'Voitures Sur Commande',
    'Oui': 'Oui',
    'Non': 'Non',
    'Manuelle': 'Manuelle',
    'Automatique': 'Automatique',
    'CVT': 'CVT',
    'Blanc': 'Blanc',
    'gris souris': 'Gris souris',
    'gris argent': 'Gris argent',
    'blanc': 'Blanc',
    'tags': 'Étiquettes',
    'price': 'Prix',
    'calling': 'Appelez-nous:',
    'energie': 'Énergie',
    'etat': 'État',
    'annee': 'Année',
    'finition': 'Finition',
    'couleurs': 'Couleurs',
    'cylindre': 'Cylindres',
    'boite': 'Boîte de vitesse',
    'abs': 'ABS',
    'Climatisation_Automatique': 'Climatisation Automatique',
    'Climatisation Automatique': 'Climatisation Automatique',
    'Toit_Ouvrant': 'Toit Ouvrant',
    'Toit Ouvrant': 'Toit Ouvrant',
    'Siège_Conducteur_Electrique': 'Siège Conducteur Électrique',
    'Siège Conducteur Electrique': 'Siège Conducteur Électrique',
    'Siège_Passager_Electrique': 'Siège Passager Électrique',
    'Siège Passager Electrique': 'Siège Passager Électrique',
    'Stationnement_automatique': 'Stationnement Automatique',
    'Stationnement automatique': 'Stationnement Automatique',
    'Radar_Stationnement_Avant': 'Radar Stationnement Avant',
    'Radar Stationnement Avant': 'Radar Stationnement Avant',
    'Radar_Stationnement_Arrier': 'Radar Stationnement Arrière',
    'Radar Stationnement Arrière': 'Radar Stationnement Arrière',
    'Assistance_Au_Freinage': 'Assistance Au Freinage',
    'Assistance Au Freinage': 'Assistance Au Freinage',
    'Siège_chauffants': 'Siège Chauffants',
    'Siège chauffants': 'Siège Chauffants',
    'Siège_climatisés': 'Siège Climatisés',
    'Siège climatisés': 'Siège Climatisés',
    'Caméra_de_recul': 'Caméra de Recul',
    'Caméra de recul': 'Caméra de Recul',
    'Écran_tactile': 'Écran Tactile',
    'Écran tactile': 'Écran Tactile',
    'Airbags_supplémentaires': 'Airbags Supplémentaires',
    'Airbags supplémentaires': 'Airbags Supplémentaires',
    'Les_gants_en_alliage': 'Les Gants en Alliage',
    'Les gants en alliage': 'Les Gants en Alliage',
    'camera_de_360_degrés': 'Caméra 360 Degrés',
    'camera de 360 degrés': 'Caméra 360 Degrés',
    'la_malle_électrique': 'La Malle Électrique',
    'la malle électrique': 'La Malle Électrique',
    'available': 'Disponible',
    'Not Available': 'Pas Disponible'
  },
  ar: {

    'order-info-title': 'معلومات حول الطلبات',
    'order-info-text': 'هذه السيارات متوفرة على الطلب. اتصل بنا للحصول على مزيد من المعلومات.',
    'no-order-cars': 'لا توجد سيارات على الطلب',
    'no-order-message': 'لا توجد سيارات متوفرة على الطلب في الوقت الحالي.',
    'about': 'حول',
    'Sur-Commande': 'على الطلب',
    'contact': 'معلومات الاتصال',
    'location': 'الموقع',
    'back': 'عودة',
    'copyright': '© 2025 سامي أوتو. جميع الحقوق محفوظة.',
    'welcome-subtitle': 'اكتشف مجموعتنا من السيارات المتوفرة فورًا أو على الطلب',
    'view-cars': 'عرض السيارات',
    'welcome-title': 'مرحبًا بكم عند سامي أوتو',
    'Voitures Disponibles': 'سيارات متوفرة',
    'available-description': 'سيارات جاهزة',
    'order-description': 'سيارات متوفرة على الطلب',
    'pret': 'جاهزة ',
    'view-more': 'عرض المزيد',
    'car-not-found': 'السيارة غير موجودة',
    'loading-error': 'خطأ في التحميل',
    'description': 'الوصف:',
    'location-btn': 'الموقع',
    'call-btn': 'اتصل',
    'phone-numbers': 'أرقام الهاتف:',
    'call': 'اتصل',
    'copy': 'نسخ',
    'copied': 'تم النسخ!',
    'other-cars': 'سيارات أخرى متاحة',
    'back-to-list': 'العودة إلى القائمة',
    'state': 'الحالة',
    'year': 'السنة',
    'finish': 'الموديل',
    'colors': 'الألوان',
    'motor': 'المحرك',
    'gearbox': 'علبة السرعات',
    'new': 'جديد',
    'used': 'مستعمل',
    'luxury': 'فخم',
    'economical': 'اقتصادي',
    'suv': 'دفع رباعي',
    'citadine': 'مدينة',
    'Energie': 'بنزين',
    'diesel': 'ديزل',
    'hybrid': 'هجين',
    'information': 'المعلومات الرئيسية',
    'details': 'تفاصيل السيارة',
    'boit_manuelle': 'يدوي',
    'technical_specs': 'المواصفات التقنية',
    'basic_details': 'التفاصيل الأساسية',
    'Power': 'القوة',
    'Cylindre': 'الأسطوانات',
    'ABS': 'ABS',
    'Radar Stationnement Avant': 'رادار ركن أمامي',
    'Radar Stationnement Arrière': 'رادار ركن خلفي',
    'Climatisation': 'تكييف الهواء',
    'Assistance Au Freinage': 'مساعدة الفرامل',
    'Contrôle De Traction': 'نظام التحكم في الجر',
    'Contrôle De Stabilité': 'نظام التحكم في الثبات',
    'toit ouvrant': 'فتحة سقف',
    'Disponible': 'متاح',
    'Sur command': 'على الطلب',
    'Voitures Sur Commande': 'سيارات على الطلب',
    'Oui': 'نعم',
    'Non': 'لا',
    'Manuelle': 'يدوي',
    'Automatique': 'أوتوماتيكي',
    'CVT': 'CVT',
    'Blanc': 'أبيض',
    'gris souris': 'رمادي فأري',
    'gris argent': 'رمادي فضي',
    'blanc': 'أبيض',
    'tags': 'العلامات',
    'price': 'السعر',
    'En': 'بنزين',
    'calling': 'اتصل بنا:',
    'energie': 'الطاقة',
    'etat': 'الحالة',
    'annee': 'السنة',
    'finition': 'الموديل',
    'couleurs': 'الألوان',
    'cylindre': 'الأسطوانات',
    'boite': 'علبة السرعات',
    'abs': 'ABS',
    'Climatisation_Automatique': 'تكييف هواء أوتوماتيكي',
    'Climatisation Automatique': 'تكييف هواء أوتوماتيكي',
    'Toit_Ouvrant': 'فتحة سقف',
    'Toit Ouvrant': 'فتحة سقف',
    'Siège_Conducteur_Electrique': 'مقعد السائق الكهربائي',
    'Siège Conducteur Electrique': 'مقعد السائق الكهربائي',
    'Siège_Passager_Electrique': 'مقعد الراكب الكهربائي',
    'Siège Passager Electrique': 'مقعد الراكب الكهربائي',
    'Stationnement_automatique': 'ركن أوتوماتيكي',
    'Stationnement automatique': 'ركن أوتوماتيكي',
    'Radar_Stationnement_Avant': 'رادار ركن أمامي',
    'Radar Stationnement Avant': 'رادار ركن أمامي',
    'Radar_Stationnement_Arrier': 'رادار ركن خلفي',
    'Radar Stationnement Arrière': 'رادار ركن خلفي',
    'Assistance_Au_Freinage': 'مساعدة الفرامل',
    'Assistance Au Freinage': 'مساعدة الفرامل',
    'Siège_chauffants': 'مقاعد مدفأة',
    'Siège chauffants': 'مقاعد مدفأة',
    'Siège_climatisés': 'مقاعد مكيفة',
    'Siège climatisés': 'مقاعد مكيفة',
    'Caméra_de_recul': 'كاميرا الرجوع للخلف',
    'Caméra de recul': 'كاميرا الرجوع للخلف',
    'Écran_tactile': 'شاشة لمس',
    'Écran tactile': 'شاشة لمس',
    'Airbags_supplémentaires': 'وسائد هوائية إضافية',
    'Airbags supplémentaires': 'وسائد هوائية إضافية',
    'Les_gants_en_alliage': 'قفازات السبائك',
    'Les gants en alliage': 'قفازات السبائك',
    'camera_de_360_degrés': 'كاميرا 360 درجة',
    'camera de 360 degrés': 'كاميرا 360 درجة',
    'la_malle_électrique': 'الصندوق الخلفي الكهربائي',
    'la malle électrique': 'الصندوق الخلفي الكهربائي',
    'available': 'متاح',
    'Not Available': 'غير متاح'
  }
};

const detailTranslations = {
  fr: {
    'Etat': 'Etat',
    'Année': 'Année',
    'Finition': 'Finition',
    'Couleurs': 'Couleurs',
    'Energie': 'Energie',
    'Motor': 'Motor',
    'Power': 'Puissance',
    'Cylindre': 'Cylindres',
    'Boite': 'Boite',
    'Voitures Disponibles': 'Voitures Disponibles',
    'ABS': 'ABS',
    'view-cars': 'Voir les voitures',
    'Radar stationnement avant': 'Radar stationnement avant',
    'Radar stationnement arrière': 'Radar stationnement arrière',
    'Climatisation': 'Climatisation',
    'Assistance Au Freinage': 'Assistance Au Freinage',
    'Contrôle De Traction': 'Contrôle de Traction',
    'Contrôle De Stabilité': 'Contrôle de Stabilité',
    'available-description': 'Voitures prêtes',
    'Camera 540°': 'Camera 540°',
    'Siège Passager Electrique': 'Siège Passager Electrique',
    'Stationnement Automatique': 'Stationnement Automatique',
    'siège Conducteur Electrique': 'siège Conducteur Electrique',
    'toit ouvrant': 'Toit ouvrant',
    'Disponible': 'Disponible',
    'pret': 'Prêt à partir',
    'Sur command': 'Sur commande',
    'Voitures Sur Commande': 'Voitures Sur Commande',
    'Oui': 'Oui',
    'Non': 'Non',
    'Manuelle': 'Manuelle',
    'Automatique': 'Automatique',
    'CVT': 'CVT',
    'Blanc': 'Blanc',
    'gris souris': 'Gris souris',
    'gris argent': 'Gris argent',
    'blanc': 'Blanc',
    'Neuf': 'Neuf',
    'Occasion': 'Occasion',
    'En': 'Essence',
    'energie': 'Énergie',
    'etat': 'État',
    'annee': 'Année',
    'finition': 'Finition',
    'couleurs': 'Couleurs',
    'motor': 'Moteur',
    'power': 'Puissance',
    'cylindre': 'Cylindres',
    'boite': 'Boîte de vitesse',
    'abs': 'ABS',
    'Climatisation_Automatique': 'Climatisation Automatique',
    'Climatisation Automatique': 'Climatisation Automatique',
    'Toit_Ouvrant': 'Toit Ouvrant',
    'Toit Ouvrant': 'Toit Ouvrant',
    'Siège_Conducteur_Electrique': 'Siège Conducteur Électrique',
    'Siège Conducteur Electrique': 'Siège Conducteur Électrique',
    'Siège_Passager_Electrique': 'Siège Passager Électrique',
    'Siège Passager Electrique': 'Siège Passager Électrique',
    'Stationnement_automatique': 'Stationnement Automatique',
    'Stationnement automatique': 'Stationnement Automatique',
    'Radar_Stationnement_Avant': 'Radar Stationnement Avant',
    'Radar Stationnement Avant': 'Radar Stationnement Avant',
    'Radar_Stationnement_Arrier': 'Radar Stationnement Arrière',
    'Radar Stationnement Arrière': 'Radar Stationnement Arrière',
    'Assistance_Au_Freinage': 'Assistance Au Freinage',
    'Assistance Au Freinage': 'Assistance Au Freinage',
    'Siège_chauffants': 'Siège Chauffants',
    'Siège chauffants': 'Siège Chauffants',
    'Siège_climatisés': 'Siège Climatisés',
    'Siège climatisés': 'Siège Climatisés',
    'Caméra_de_recul': 'Caméra de Recul',
    'Caméra de recul': 'Caméra de Recul',
    'Écran_tactile': 'Écran Tactile',
    'Écran tactile': 'Écran Tactile',
    'Airbags_supplémentaires': 'Airbags Supplémentaires',
    'Airbags supplémentaires': 'Airbags Supplémentaires',
    'Les_gants_en_alliage': 'Les Gants en Alliage',
    'Les gants en alliage': 'Les Gants en Alliage',
    'camera_de_360_degrés': 'Caméra 360 Degrés',
    'camera de 360 degrés': 'Caméra 360 Degrés',
    'la_malle_électrique': 'La Malle Électrique',
    'la malle électrique': 'La Malle Électrique',
    'available': 'Disponible',
    'Not Available': 'Pas Disponible'
  },
  ar: {
    'Etat': 'الحالة',
    'Année': 'السنة',
    'Finition': 'الموديل',
    'Couleurs': 'الألوان',
    'Energie': 'الوقود',
    'Motor': 'المحرك',
    'Power': 'القوة',
    'Cylindre': 'الأسطوانات',
    'Boite': 'ناقل الحركة',
    'ABS': 'ABS',
    'Voitures Disponibles': 'سيارات متوفرة',
    'view-cars': 'عرض السيارات',
    'Radar Stationnement Avant': 'رادار ركن أمامي',
    'Radar Stationnement Arrière': 'رادار ركن خلفي',
    'Climatisation': 'تكييف الهواء',
    'Toit Ouvrant': 'فتحة سقف',
    'Assistance Au Freinage': 'مساعدة الفرامل',
    'Contrôle De Traction': 'نظام التحكم في الجر',
    'Contrôle De Stabilité': 'نظام التحكم في الثبات',
    'Siège Passager Electrique': 'مقعد الراكب كهربائي',
    'Camera 540°': 'كاميرا 540°',
    'Stationnement Automatique': 'ركن أوتوماتيكي',
    'siège Conducteur Electrique': 'مقعد السائق كهربائي',
    'toit ouvrant': 'فتحة سقف',
    'Disponible': 'متاح',
    'Sur command': 'على الطلب',
    'available-description': 'سيارات جاهزة',
    'Voitures Sur Commande': 'سيارات على الطلب',
    'pret': 'جاهزة',
    'Oui': 'نعم',
    'Non': 'لا',
    'Manuelle': 'يدوي',
    'Automatique': 'أوتوماتيكي',
    'CVT': 'CVT',
    'Blanc': 'أبيض',
    'blanc': 'أبيض',
    'Neuf': 'جديد',
    'Occasion': 'مستعمل',
    'En': 'بنزين',
    'energie': 'الطاقة',
    'etat': 'الحالة',
    'annee': 'السنة',
    'finition': 'الموديل',
    'couleurs': 'الألوان',
    'motor': 'المحرك',
    'power': 'القوة',
    'cylindre': 'الأسطوانات',
    'boite': 'علبة السرعات',
    'abs': 'ABS',
    'Climatisation_Automatique': 'تكييف هواء أوتوماتيكي',
    'Climatisation Automatique': 'تكييف هواء أوتوماتيكي',
    'Toit_Ouvrant': 'فتحة سقف',
    'Toit Ouvrant': 'فتحة سقف',
    'Siège_Conducteur_Electrique': 'مقعد السائق الكهربائي',
    'Siège Conducteur Electrique': 'مقعد السائق الكهربائي',
    'Siège_Passager_Electrique': 'مقعد الراكب الكهربائي',
    'Siège Passager Electrique': 'مقعد الراكب الكهربائي',
    'Stationnement_automatique': 'ركن أوتوماتيكي',
    'Stationnement automatique': 'ركن أوتوماتيكي',
    'Radar_Stationnement_Avant': 'رادار ركن أمامي',
    'Radar Stationnement Avant': 'رادار ركن أمامي',
    'Radar_Stationnement_Arrier': 'رادار ركن خلفي',
    'Radar Stationnement Arrière': 'رادار ركن خلفي',
    'Assistance_Au_Freinage': 'مساعدة الفرامل',
    'Assistance Au Freinage': 'مساعدة الفرامل',
    'Siège_chauffants': 'مقاعد مدفأة',
    'Siège chauffants': 'مقاعد مدفأة',
    'Siège_climatisés': 'مقاعد مكيفة',
    'Siège climatisés': 'مقاعد مكيفة',
    'Caméra_de_recul': 'كاميرا الرجوع للخلف',
    'Caméra de recul': 'كاميرا الرجوع للخلف',
    'Écran_tactile': 'شاشة لمس',
    'Écran tactile': 'شاشة لمس',
    'Airbags_supplémentaires': 'وسائد هوائية إضافية',
    'Airbags supplémentaires': 'وسائد هوائية إضافية',
    'Les_gants_en_alliage': 'قفازات السبائك',
    'Les gants en alliage': 'قفازات السبائك',
    'camera_de_360_degrés': 'كاميرا 360 درجة',
    'camera de 360 degrés': 'كاميرا 360 درجة',
    'la_malle_électrique': 'الصندوق الخلفي الكهربائي',
    'la malle électrique': 'الصندوق الخلفي الكهربائي',
    'available': 'متاح',
    'Not Available': 'غير متاح'
  }
};

let currentLanguage = localStorage.getItem('language') || 'fr';

document.addEventListener('DOMContentLoaded', () => {
  setLanguage(currentLanguage);
  
  const languageToggle = document.getElementById('language-toggle');
  if (languageToggle) {
    languageToggle.addEventListener('click', () => {
      currentLanguage = currentLanguage === 'fr' ? 'ar' : 'fr';
      setLanguage(currentLanguage);
      localStorage.setItem('language', currentLanguage);
      window.location.reload();
    });
  }
});

function setLanguage(lang) {
  const html = document.documentElement;
  
  html.setAttribute('lang', lang);
  html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
  
  const nextLangSpan = document.getElementById('next-lang');
  if (nextLangSpan) {
    nextLangSpan.textContent = lang === 'fr' ? 'AR' : 'FR';
  }
  
  document.title = translations[lang]['page-title'] || document.title;
  
  const translatableElements = document.querySelectorAll('[data-translate]');
  translatableElements.forEach(element => {
    const key = element.getAttribute('data-translate');
    if (translations[lang][key]) {
      element.textContent = translations[lang][key];
    }
  });
  
  document.body.classList.toggle('rtl', lang === 'ar');
  document.body.classList.toggle('ltr', lang === 'fr');
}

function getTranslation(key) {
  return translations[currentLanguage][key] || key;
}

function getDetailTranslation(key) {
  return detailTranslations[currentLanguage][key] || key;
}

function translateValue(value, context = null) {
  if (value === 'available' || value === 'Not Available') {
    return getTranslation(value);
  }
  
  const commonTranslations = {
    'Neuf': currentLanguage === 'ar' ? 'جديد' : 'Neuf',
    'Occasion': currentLanguage === 'ar' ? 'مستعمل' : 'Occasion',
    'Manuelle': currentLanguage === 'ar' ? 'يدوي' : 'Manuelle',
    'Automatique': currentLanguage === 'ar' ? 'أوتوماتيكي' : 'Automatique',
    'CVT': 'CVT',
    'Blanc': currentLanguage === 'ar' ? 'أبيض' : 'Blanc',
    'blanc': currentLanguage === 'ar' ? 'أبيض' : 'Blanc',
    'En': currentLanguage === 'ar' ? 'بنزين' : 'Essence',
    'Diesel': currentLanguage === 'ar' ? 'ديزل' : 'Diesel',
    'Oui': currentLanguage === 'ar' ? 'نعم' : 'Oui',
    'Non': currentLanguage === 'ar' ? 'لا' : 'Non'
  };
  
  return commonTranslations[value] || value;
}

window.getTranslation = getTranslation;
window.getDetailTranslation = getDetailTranslation;
window.getCurrentLanguage = () => currentLanguage;
window.translateValue = translateValue;